package io.github.mkxpz.rpgplayer.domain

import io.github.mkxpz.rpgplayer.data.GameEntry
import io.github.mkxpz.rpgplayer.data.LauncherSettings
import io.github.mkxpz.rpgplayer.data.RpgMakerEngine
import io.github.mkxpz.rpgplayer.data.isRgss
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.Locale

class MkxpConfigWriter {
    fun writeConfig(entry: GameEntry, settings: LauncherSettings, output: File): File {
        output.parentFile?.mkdirs()
        if (entry.engine.isRgss() && entry.hasEncryptedArchive) {
            runCatching {
                PackedRgssGameExtractor.materializeCriticalAssets(File(entry.installedPath))
            }
        }

        val rtpPaths = resolveRtpPaths(entry, settings)
        val json = JSONObject()
            .put("gameFolder", entry.installedPath)
            .put("rgssVersion", entry.engine.rgssVersion)
            .put("windowTitle", entry.title)
            .put("fullscreen", true)
            .put("fixedAspectRatio", settings.keepAspectRatio)
            .put("smoothScaling", settings.smoothScaling)
            .put("pathCache", shouldUsePathCache(entry, rtpPaths))
            .put("fixedFramerate", settings.fixedFramerate)
            .put("displayFPS", settings.debugLaunch)
            .put("printFPS", settings.debugLaunch)
            .put("vsync", false)
            .put("frameSkip", false)
            .put("subImageFix", true)

        resolveSoundFont(entry, settings, rtpPaths)?.let { soundFont ->
            json.put("midiSoundFont", soundFont)
        }
        rtpPaths.takeIf { it.isNotEmpty() }?.let { rtps ->
            json.put("RTP", JSONArray(rtps))
        }
        if (!entry.customIconPath.isNullOrBlank()) {
            json.put("iconPath", entry.customIconPath)
        }

        val preloadScripts = JSONArray()
        if (settings.rubyClassicCompatibilityEnabled && entry.engine.isRgss()) {
            json.put("useScriptNames", true)
            preloadScripts.put(writeRubyClassicCompatibilityScript(output).absolutePath)
        }
        if (entry.engine.isRgss()) {
            preloadScripts.put(writeAndroidStorageCompatibilityScript(entry, output).absolutePath)
        }
        if (settings.winApiCompatibilityEnabled && entry.engine.isRgss() && entry.hasWinApiUsage) {
            preloadScripts.put(writeWinApiCompatibilityScript(output).absolutePath)
        }
        if (entry.engine.isRgss()) {
            preloadScripts.put(writeModifierCompatibilityScript(output).absolutePath)
        }
        if (preloadScripts.length() > 0) {
            json.put("preloadScript", preloadScripts)
        }

        output.writeTextIfChanged(json.toString(2))
        return output
    }

    private fun writeRubyClassicCompatibilityScript(output: File): File {
        val script = File(output.parentFile ?: output.absoluteFile.parentFile, "ruby_classic_compat.rb")
        script.parentFile?.mkdirs()
        script.writeTextIfChanged(
            """
            # Generated by mkxp-z Player.
            class Hash
              alias_method :index, :key unless method_defined?(:index)
            end

            class Object
              TRUE = true unless const_defined?("TRUE")
              FALSE = false unless const_defined?("FALSE")
              NIL = nil unless const_defined?("NIL")

              alias_method :id, :object_id unless method_defined?(:id)
              alias_method :type, :class unless method_defined?(:type)
            end

            class NilClass
              def id
                4
              end
            end

            class TrueClass
              def id
                2
              end
            end

            if defined?(BasicObject) && BasicObject.instance_method(:initialize).arity == 0
              class BasicObject
                def initialize(*args)
                end
              end
            end

            module MKXPZPlayerCompat
              RUBY_CLASSIC_COMPATIBILITY = true
            end
            """.trimIndent(),
        )
        return script
    }

    private fun shouldUsePathCache(entry: GameEntry, rtpPaths: List<String>): Boolean {
        if (!entry.engine.isRgss()) return false
        if (entry.hasEncryptedArchive) return true
        if (rtpPaths.isNotEmpty()) return true
        return entry.engine == RpgMakerEngine.UNKNOWN
    }

    private fun resolveSoundFont(entry: GameEntry, settings: LauncherSettings, rtpPaths: List<String>): String? {
        settings.soundFontPath.trim().takeIf { it.isNotBlank() }?.let { return it }

        findSoundFont(File(entry.installedPath))?.let { return it.absolutePath }
        rtpPaths.asSequence()
            .mapNotNull { findSoundFont(File(it)) }
            .firstOrNull()
            ?.let { return it.absolutePath }

        return null
    }

    private fun resolveRtpPaths(entry: GameEntry, settings: LauncherSettings): List<String> {
        return resolveRtpPaths(entry, settings, null)
    }

    private fun resolveRtpPaths(entry: GameEntry, settings: LauncherSettings, explicitFilesDir: File?): List<String> {
        if (!entry.needsRtp()) return emptyList()

        val filesDir = explicitFilesDir ?: inferFilesDirFromConfigPath(File(entry.configPath))
        val appVxRtp = filesDir?.resolve("rtp/vx")
        val appVxAceRtp = filesDir?.resolve("rtp/vxace")

        return buildList {
            when (entry.engine) {
                RpgMakerEngine.VX -> {
                    addRtpPath(settings.vxRtpPath)
                    addRtpPath(appVxRtp?.absolutePath.orEmpty())
                }
                RpgMakerEngine.VX_ACE -> {
                    addRtpPath(settings.vxAceRtpPath)
                    addRtpPath(appVxAceRtp?.absolutePath.orEmpty())
                    addRtpPath(settings.vxRtpPath)
                    addRtpPath(appVxRtp?.absolutePath.orEmpty())
                }
                else -> Unit
            }
        }
    }

    private fun GameEntry.needsRtp(): Boolean {
        if (!engine.isRgss()) return false
        if (hasEncryptedArchive) return true
        val rtp = runCatching {
            val gameIni = File(installedPath, "Game.ini").takeIf(File::isFile) ?: return false
            parseIniValue(gameIni.readText(), "RTP")
        }.getOrDefault("")
        return rtp.isNotBlank()
    }

    private fun MutableList<String>.addRtpPath(path: String) {
        val normalized = findRtpRoot(File(path.trim())) ?: return
        val absolutePath = normalized.absolutePath
        if (none { it == absolutePath }) {
            add(absolutePath)
        }
    }

    private fun inferFilesDirFromConfigPath(configPath: File): File? {
        val configsDir = configPath.parentFile?.parentFile
        if (configsDir?.name != "configs") return null
        return configsDir.parentFile
    }

    private fun findRtpRoot(root: File?, depth: Int = 0): File? {
        if (root == null || !root.isDirectory) return null
        val children = root.listFiles().orEmpty()
        val names = children.map { it.name.lowercase(Locale.US) }.toSet()
        if ("audio" in names && "graphics" in names) {
            return root
        }
        if (depth >= 3) return null
        return children
            .asSequence()
            .filter { it.isDirectory }
            .mapNotNull { findRtpRoot(it, depth + 1) }
            .firstOrNull()
    }

    private fun findSoundFont(root: File): File? {
        if (!root.isDirectory) return null

        soundFontCommonDirectories
            .asSequence()
            .map { name -> if (name.isBlank()) root else root.resolve(name) }
            .mapNotNull { directory -> findSoundFontInDirectory(directory) }
            .firstOrNull()
            ?.let { return it }

        return root.listFiles()
            .orEmpty()
            .asSequence()
            .filter { file ->
                file.isDirectory && file.name.lowercase(Locale.US) in soundFontSearchDirectories
            }
            .flatMap { directory -> directory.walkTopDown().maxDepth(3).asSequence() }
            .firstOrNull { file -> file.isFile && file.extension.lowercase(Locale.US) in soundFontExtensions }
    }

    private fun findSoundFontInDirectory(directory: File): File? {
        if (!directory.isDirectory) return null
        return directory.listFiles()
            .orEmpty()
            .firstOrNull { file -> file.isFile && file.extension.lowercase(Locale.US) in soundFontExtensions }
    }

    private fun writeAndroidStorageCompatibilityScript(entry: GameEntry, output: File): File {
        val script = File(output.parentFile ?: output.absoluteFile.parentFile, "android_storage_compat.rb")
        val saveRoot = File(output.parentFile ?: output.absoluteFile.parentFile, "saves").absolutePath
        val gameRoot = entry.installedPath
        script.parentFile?.mkdirs()
        script.writeTextIfChanged(
            """
            # Generated by mkxp-z Player.
            module MKXPZPlayerCompat
              SAVE_ROOT = ${saveRoot.rubyStringLiteral}
              GAME_ROOT = ${gameRoot.rubyStringLiteral}

              module_function

              def normalize_android_path(path)
                path.to_s.tr("\\", "/")
              end

              def relative_save_path(path)
                normalized = normalize_android_path(path)
                game = normalize_android_path(GAME_ROOT)
                normalized = normalized[(game.length + 1)..-1] if normalized.start_with?(game + "/")
                normalized = normalized.sub(%r{\A\./}, "")
                return nil unless save_like_path?(normalized)
                normalized
              end

              def save_like_path?(path)
                value = normalize_android_path(path).downcase
                return true if value.start_with?("save/")
                return true if value.start_with?("saves/")
                return true if value.include?("/save/")
                return true if value.include?("/saves/")
                return true if value =~ %r{\Asave\d*[^/]*\.(rvdata2?|rxdata|dat)\z}
                return true if value =~ %r{/(save\d*[^/]*)\.(rvdata2?|rxdata|dat)\z}
                false
              end

              def redirected_save_path(path)
                relative = relative_save_path(path)
                return nil unless relative
                File.join(SAVE_ROOT, relative)
              end

              def ensure_parent(path)
                dir = File.dirname(path.to_s)
                Dir.mkdir(dir) unless File.directory?(dir)
              rescue Errno::ENOENT
                parent = File.dirname(dir)
                ensure_parent(parent) unless parent == dir
                Dir.mkdir(dir) unless File.directory?(dir)
              rescue
              end

              def writable_path(path)
                target = redirected_save_path(path)
                return path.to_s unless target
                ensure_parent(target)
                target
              end

              def readable_path(path)
                target = redirected_save_path(path)
                return target if target && File.exist?(target)
                path.to_s
              end

              def safe_create_placeholder_png(path)
                return 0 if path.to_s.empty?
                target = writable_path(path)
                ensure_parent(target)
                return 1 if File.exist?(target)
                png = [
                  0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A,
                  0x00,0x00,0x00,0x0D,0x49,0x48,0x44,0x52,
                  0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
                  0x08,0x06,0x00,0x00,0x00,0x1F,0x15,0xC4,0x89,
                  0x00,0x00,0x00,0x0A,0x49,0x44,0x41,0x54,
                  0x78,0x9C,0x63,0x00,0x01,0x00,0x00,0x05,0x00,0x01,
                  0x0D,0x0A,0x2D,0xB4,0x00,0x00,0x00,0x00,
                  0x49,0x45,0x4E,0x44,0xAE,0x42,0x60,0x82
                ].pack("C*")
                File.open(target, "wb") { |file| file.write(png) }
                1
              rescue
                0
              end
            end

            Dir.mkdir(MKXPZPlayerCompat::SAVE_ROOT) unless File.directory?(MKXPZPlayerCompat::SAVE_ROOT) rescue nil
            Dir.mkdir("Save") unless File.directory?("Save") rescue nil
            Dir.mkdir("Saves") unless File.directory?("Saves") rescue nil

            module Kernel
              if method_defined?(:save_data) && !method_defined?(:mkxpz_player_save_data_without_android_storage)
                alias_method :mkxpz_player_save_data_without_android_storage, :save_data
                def save_data(obj, filename)
                  mkxpz_player_save_data_without_android_storage(obj, MKXPZPlayerCompat.writable_path(filename))
                end
              end

              if method_defined?(:load_data) && !method_defined?(:mkxpz_player_load_data_without_android_storage)
                alias_method :mkxpz_player_load_data_without_android_storage, :load_data
                def load_data(filename, raw = false)
                  mkxpz_player_load_data_without_android_storage(MKXPZPlayerCompat.readable_path(filename), raw)
                end
              end
            end

            class << File
              unless method_defined?(:mkxpz_player_open_without_android_storage)
                alias_method :mkxpz_player_open_without_android_storage, :open
                def open(path, mode = "r", *args, &block)
                  mode_text = mode.to_s
                  actual = if mode_text =~ /[wa+]/
                    MKXPZPlayerCompat.writable_path(path)
                  else
                    MKXPZPlayerCompat.readable_path(path)
                  end
                  mkxpz_player_open_without_android_storage(actual, mode, *args, &block)
                end
              end

              unless method_defined?(:mkxpz_player_exist_without_android_storage)
                alias_method :mkxpz_player_exist_without_android_storage, :exist?
                def exist?(path)
                  redirected = MKXPZPlayerCompat.redirected_save_path(path)
                  return true if redirected && mkxpz_player_exist_without_android_storage(redirected)
                  mkxpz_player_exist_without_android_storage(path)
                end
                alias exists? exist? if method_defined?(:exists?)
              end

              unless method_defined?(:mkxpz_player_delete_without_android_storage)
                alias_method :mkxpz_player_delete_without_android_storage, :delete
                def delete(*paths)
                  mkxpz_player_delete_without_android_storage(*paths.map { |path| MKXPZPlayerCompat.readable_path(path) })
                end
              end
            end

            module MKXPZPlayerCompat
              ANDROID_STORAGE_COMPATIBILITY = true
            end
            """.trimIndent(),
        )
        return script
    }

    private fun writeWinApiCompatibilityScript(output: File): File {
        val script = File(output.parentFile ?: output.absoluteFile.parentFile, "winapi_compat.rb")
        script.parentFile?.mkdirs()
        script.writeTextIfChanged(
            """
            # Generated by mkxp-z Player.
            module MKXPZPlayerCompat
              NativeWin32API = ::Win32API if defined?(::Win32API) && !const_defined?(:NativeWin32API)

              WINDOWS_DLLS = [
                "kernel32", "user32", "gdi32", "shell32", "advapi32", "ole32",
                "oleaut32", "winmm", "comdlg32", "shlwapi"
              ]
              GAME_WINDOW_HANDLE = 1
              DESKTOP_WINDOW_HANDLE = 2
              FOREGROUND_WINDOW_HANDLE = GAME_WINDOW_HANDLE

              module_function

              def normalize_library_name(name)
                value = name.to_s.downcase
                value = value.sub(/\.dll\z/i, "")
                value.tr("\\", "/").split("/").last.to_s
              end

              def windows_library?(name)
                WINDOWS_DLLS.include?(normalize_library_name(name))
              end

              def tktk_bitmap_library?(name)
                normalize_library_name(name) == "tktk_bitmap"
              end

              def safe_path(path)
                path.to_s.tr("\\", "/")
              end

              def android_metrics
                if defined?(Android) && Android.respond_to?(:display_metrics)
                  Android.display_metrics
                else
                  {}
                end
              rescue
                {}
              end

              def metric_value(metrics, key, fallback)
                metrics[key] || metrics[key.to_s] || fallback
              end

              def game_width
                defined?(Graphics) && Graphics.respond_to?(:width) ? Graphics.width : 816
              end

              def game_height
                defined?(Graphics) && Graphics.respond_to?(:height) ? Graphics.height : 624
              end

              def desktop_width
                metric_value(android_metrics, :width_pixels, game_width).to_i
              end

              def desktop_height
                metric_value(android_metrics, :height_pixels, game_height).to_i
              end

              def density
                metric_value(android_metrics, :density, 1.0).to_f
              end

              def game_window_rect
                @game_window_rect ||= [0, 0, game_width, game_height]
              end

              def set_game_window_rect(left, top, right, bottom)
                @game_window_rect = [left.to_i, top.to_i, right.to_i, bottom.to_i]
              end

              def write_rect(buffer, left, top, right, bottom)
                return unless buffer.respond_to?(:replace)
                buffer.replace([left, top, right, bottom].pack("l4"))
              end

              def read_ini_value(section, key, default_value, file)
                path = safe_path(file)
                path = "Game.ini" if path.empty?
                text = File.file?(path) ? File.read(path) : ""
                current = nil
                text.each_line do |line|
                  stripped = line.strip
                  if stripped.start_with?("[") && stripped.end_with?("]")
                    current = stripped[1...-1]
                    next
                  end
                  next unless current.to_s.casecmp(section.to_s).zero?
                  name, value = stripped.split("=", 2)
                  return value.to_s.strip if name && name.casecmp(key.to_s).zero?
                end
                default_value.to_s
              rescue
                default_value.to_s
              end

              def write_string_buffer(buffer, value, size)
                return unless buffer.respond_to?(:replace)
                max = [size.to_i - 1, 0].max
                data = value.to_s.byteslice(0, max).to_s
                buffer.replace(data + 0.chr)
              end

              def copy_file(source, destination, fail_if_exists)
                source_path = safe_path(source)
                destination_path = safe_path(destination)
                return 0 if fail_if_exists.to_i != 0 && File.exist?(destination_path)
                input = File.open(source_path, "rb")
                begin
                  output = File.open(destination_path, "wb")
                  begin
                    while (chunk = input.read(64 * 1024))
                      output.write(chunk)
                    end
                  ensure
                    output.close
                  end
                ensure
                  input.close
                end
                1
              rescue
                0
              end

              def default_return(exports)
                exports.to_s.downcase.start_with?("p") ? "" : 0
              end

              def call_tktk_bitmap_api(function, exports, args)
                name = function.to_s.downcase
                case name
                when "pngsavea", "pngsavew", "pngsave"
                  path = args.find { |arg| arg.is_a?(String) }.to_s
                  return MKXPZPlayerCompat.safe_create_placeholder_png(path) if MKXPZPlayerCompat.respond_to?(:safe_create_placeholder_png)
                  1
                when "getgamehwnd"
                  GAME_WINDOW_HANDLE
                when "getaddress", "getpixeldata"
                  1
                when "setpixeldata", "blur", "changetone", "clipmask", "invertcolor", "mosaic", "blendblt", "changesize"
                  1
                else
                  default_return(exports)
                end
              end

              def remember_android_window_rect(width, height)
                width = width.to_i
                height = height.to_i
                return if width <= 0 || height <= 0
                return if width > 4096 || height > 4096
                set_game_window_rect(0, 0, width, height)
              rescue
                set_game_window_rect(0, 0, width, height)
              end

              def call_windows_api(library, function, exports, args)
                return call_tktk_bitmap_api(function, exports, args) if tktk_bitmap_library?(library)

                name = function.to_s.downcase
                case name
                when "findwindowa", "findwindoww", "findwindow"
                  GAME_WINDOW_HANDLE
                when "getdesktopwindow"
                  DESKTOP_WINDOW_HANDLE
                when "getforegroundwindow"
                  FOREGROUND_WINDOW_HANDLE
                when "setwindowpos"
                  flags = args[6].to_i
                  no_size = (flags & 0x01) != 0
                  remember_android_window_rect(args[4], args[5]) unless no_size
                  1
                when "movewindow"
                  remember_android_window_rect(args[3], args[4])
                  1
                when "keybd_event"
                  1
                when "systemparametersinfoa", "systemparametersinfow", "systemparametersinfo"
                  write_rect(args[2], 0, 0, desktop_width, desktop_height)
                  1
                when "getwindowlonga", "getwindowlongw", "getwindowlong"
                  0
                when "getsystemmetrics"
                  metric = args[0].to_i
                  return desktop_width if metric == 0
                  return desktop_height if metric == 1
                  return 0 if metric == 4
                  return 0 if metric == 7 || metric == 8
                  return (48 * density).to_i if metric == 49
                  return 0
                when "getclientrect"
                  if args[0].to_i == DESKTOP_WINDOW_HANDLE
                    write_rect(args[1], 0, 0, desktop_width, desktop_height)
                  else
                    write_rect(args[1], 0, 0, game_width, game_height)
                  end
                  1
                when "getwindowrect"
                  if args[0].to_i == DESKTOP_WINDOW_HANDLE
                    write_rect(args[1], 0, 0, desktop_width, desktop_height)
                  else
                    rect = game_window_rect
                    write_rect(args[1], rect[0], rect[1], rect[2], rect[3])
                  end
                  1
                when "getprivateprofilestringa", "getprivateprofilestringw", "getprivateprofilestring"
                  value = read_ini_value(args[0], args[1], args[2], args[5])
                  write_string_buffer(args[3], value, args[4])
                  value.length
                when "writeprivateprofilestringa", "writeprivateprofilestringw", "writeprivateprofilestring"
                  1
                when "copyfilea", "copyfilew", "copyfile"
                  copy_file(args[0], args[1], args[2])
                when "rtlmovememory", "copymemory", "movememory"
                  if args[0].respond_to?(:replace) && args[1].is_a?(String)
                    args[0].replace(args[1].byteslice(0, args[2].to_i).to_s)
                  end
                  1
                else
                  default_return(exports)
                end
              end
            end

            Object.send(:remove_const, :Win32API) if Object.const_defined?(:Win32API)
            class Win32API
              def initialize(library, function, imports = nil, exports = nil)
                @library = library.to_s
                @function = function.to_s
                @exports = exports
                @native = nil

                native_class = MKXPZPlayerCompat.const_defined?(:NativeWin32API) ? MKXPZPlayerCompat.const_get(:NativeWin32API) : nil
                if native_class && !MKXPZPlayerCompat.windows_library?(@library)
                  begin
                    @native = native_class.new(library, function, imports, exports)
                  rescue
                    @native = nil
                  end
                end
              end

              def call(*args)
                return @native.call(*args) if @native
                MKXPZPlayerCompat.call_windows_api(@library, @function, @exports, args)
              end

              alias Call call
            end

            if Object.const_defined?(:WinAPI)
              Object.send(:remove_const, :WinAPI)
            end
            WinAPI = Win32API

            module MKXPZPlayerCompat
              WINAPI_COMPATIBILITY = true
            end
            """.trimIndent(),
        )
        return script
    }

    private fun writeModifierCompatibilityScript(output: File): File {
        val script = File(output.parentFile ?: output.absoluteFile.parentFile, "modifier_compat.rb")
        val config = File(output.parentFile ?: output.absoluteFile.parentFile, "modifier.properties")
        if (!config.isFile) {
            config.parentFile?.mkdirs()
            config.writeTextIfChanged(
                """
                infiniteHp=0
                infiniteMp=0
                instantKill=0
                noClip=0
                allItems=0
                goldEnabled=0
                gold=999999
                expEnabled=0
                exp=999999
                applyNonce=0
                """.trimIndent(),
            )
        }
        script.parentFile?.mkdirs()
        script.writeTextIfChanged(
            """
            # Generated by mkxp-z Player.
            module MKXPZPlayerModifier
              CONFIG_PATH = ${config.absolutePath.rubyStringLiteral}
              CONFIG_RELOAD_INTERVAL = 15

              @config = {}
              @config_loaded = false
              @mtime = nil
              @last_apply_nonce = nil
              @active = false
              @tick_count = 0
              @last_config_check_tick = -CONFIG_RELOAD_INTERVAL
              @patched_player = false
              @patched_instant_kill = false

              module_function

              def truthy?(value)
                text = value.to_s.downcase
                text == "1" || text == "true" || text == "yes"
              end

              def modifier_active?(config)
                ["infiniteHp", "infiniteMp", "instantKill", "noClip", "allItems", "goldEnabled", "expEnabled"].any? do |key|
                  truthy?(config[key])
                end
              rescue
                false
              end

              def load_config(force = false)
                if !force && @config_loaded && (@tick_count.to_i - @last_config_check_tick.to_i) < CONFIG_RELOAD_INTERVAL
                  return @config
                end
                @last_config_check_tick = @tick_count.to_i
                mtime = File.exist?(CONFIG_PATH) ? File.mtime(CONFIG_PATH).to_i : 0
                return @config if @config_loaded && @mtime == mtime
                @mtime = mtime
                parsed = {}
                if File.exist?(CONFIG_PATH)
                  File.open(CONFIG_PATH, "rb") do |file|
                    file.each_line do |line|
                      key, value = line.strip.split("=", 2)
                      parsed[key.to_s] = value.to_s if key && value
                    end
                  end
                end
                @config = parsed
                @config_loaded = true
                @active = modifier_active?(@config)
              rescue
                @config ||= {}
                @config_loaded = true
                @active = modifier_active?(@config)
              end

              def enabled?(key)
                truthy?(load_config[key])
              end

              def int_value(key, fallback = 0)
                value = load_config[key].to_i
                value < 0 ? fallback : value
              rescue
                fallback
              end

              def nonce
                int_value("applyNonce", 0)
              end

              def party_members
                return [] unless defined?(${'$'}game_party) && ${'$'}game_party
                if ${'$'}game_party.respond_to?(:members)
                  return ${'$'}game_party.members.compact
                end
                if ${'$'}game_party.respond_to?(:actors)
                  actors = ${'$'}game_party.actors
                  return actors.compact unless actors.empty? || actors.first.is_a?(Integer)
                  return actors.map { |id| defined?(${'$'}game_actors) && ${'$'}game_actors ? ${'$'}game_actors[id] : nil }.compact
                end
                []
              rescue
                []
              end

              def actor_max_hp(actor)
                return actor.mhp if actor.respond_to?(:mhp)
                return actor.maxhp if actor.respond_to?(:maxhp)
                return actor.max_hp if actor.respond_to?(:max_hp)
                nil
              end

              def actor_max_mp(actor)
                return actor.mmp if actor.respond_to?(:mmp)
                return actor.maxmp if actor.respond_to?(:maxmp)
                return actor.maxsp if actor.respond_to?(:maxsp)
                return actor.max_sp if actor.respond_to?(:max_sp)
                nil
              end

              def apply_actor(actor)
                if enabled?("infiniteHp") && actor.respond_to?(:hp=)
                  max = actor_max_hp(actor)
                  actor.hp = max if max
                end
                if enabled?("infiniteMp")
                  max = actor_max_mp(actor)
                  if max && actor.respond_to?(:mp=)
                    actor.mp = max
                  elsif max && actor.respond_to?(:sp=)
                    actor.sp = max
                  end
                end
              rescue
              end

              def gain_gold(target)
                return unless defined?(${'$'}game_party) && ${'$'}game_party
                current = ${'$'}game_party.respond_to?(:gold) ? ${'$'}game_party.gold.to_i : (${'$'}game_party.instance_variable_get(:@gold).to_i rescue 0)
                delta = target.to_i - current
                return if delta == 0
                if ${'$'}game_party.respond_to?(:gain_gold)
                  ${'$'}game_party.gain_gold(delta)
                else
                  ${'$'}game_party.instance_variable_set(:@gold, target.to_i)
                end
              rescue
              end

              def gain_all_items
                return unless defined?(${'$'}game_party) && ${'$'}game_party
                [defined?(${'$'}data_items) ? ${'$'}data_items : nil, defined?(${'$'}data_weapons) ? ${'$'}data_weapons : nil, defined?(${'$'}data_armors) ? ${'$'}data_armors : nil].compact.each do |group|
                  group.compact.each do |item|
                    next unless item
                    begin
                      if ${'$'}game_party.respond_to?(:gain_item)
                        begin
                          ${'$'}game_party.gain_item(item, 99, true)
                        rescue ArgumentError
                          begin
                            ${'$'}game_party.gain_item(item, 99)
                          rescue
                            ${'$'}game_party.gain_item(item.id, 99) if item.respond_to?(:id)
                          end
                        end
                      elsif item.respond_to?(:id)
                        if group.equal?(${'$'}data_weapons) && ${'$'}game_party.respond_to?(:gain_weapon)
                          ${'$'}game_party.gain_weapon(item.id, 99)
                        elsif group.equal?(${'$'}data_armors) && ${'$'}game_party.respond_to?(:gain_armor)
                          ${'$'}game_party.gain_armor(item.id, 99)
                        elsif ${'$'}game_party.respond_to?(:gain_item)
                          ${'$'}game_party.gain_item(item.id, 99)
                        end
                      end
                    rescue
                    end
                  end
                end
              rescue
              end

              def set_exp(target)
                party_members.each do |actor|
                  begin
                    if actor.respond_to?(:change_exp)
                      begin
                        actor.change_exp(target, false)
                      rescue ArgumentError
                        actor.change_exp(target)
                      end
                    elsif actor.respond_to?(:exp=)
                      actor.exp = target
                    end
                  rescue
                  end
                end
              end

              def patch_player
                return if @patched_player
                patched = false
                [defined?(Game_Player) ? Game_Player : nil, defined?(Game_CharacterBase) ? Game_CharacterBase : nil, defined?(Game_Character) ? Game_Character : nil].compact.each do |klass|
                  next unless klass.method_defined?(:passable?)
                  next if klass.method_defined?(:mkxpz_modifier_passable_without_noclip)
                  klass.class_eval do
                    alias_method :mkxpz_modifier_passable_without_noclip, :passable?
                    def passable?(*args)
                      return true if MKXPZPlayerModifier.enabled?("noClip")
                      mkxpz_modifier_passable_without_noclip(*args)
                    end
                  end
                  patched = true
                end
                @patched_player = patched
              rescue
              end

              def patch_instant_kill
                return if @patched_instant_kill
                patched = false
                [defined?(Game_Enemy) ? Game_Enemy : nil].compact.each do |klass|
                  next unless klass.method_defined?(:hp=)
                  next if klass.method_defined?(:mkxpz_modifier_hp_without_instant_kill)
                  klass.class_eval do
                    alias_method :mkxpz_modifier_hp_without_instant_kill, :hp=
                    def hp=(value)
                      begin
                        if MKXPZPlayerModifier.enabled?("instantKill")
                          current = respond_to?(:hp) ? hp.to_i : (@hp.to_i rescue 0)
                          value = 0 if value.to_i < current
                        end
                      rescue
                      end
                      self.mkxpz_modifier_hp_without_instant_kill(value)
                    end
                  end
                  patched = true
                end
                @patched_instant_kill = patched
              rescue
              end

              def apply_noclip
                return unless enabled?("noClip")
                return unless defined?(${'$'}game_player) && ${'$'}game_player
                if ${'$'}game_player.respond_to?(:through=)
                  ${'$'}game_player.through = true
                else
                  ${'$'}game_player.instance_variable_set(:@through, true)
                end
              rescue
              end

              def tick
                @tick_count = @tick_count.to_i + 1
                load_config
                return unless @active
                patch_player if enabled?("noClip")
                patch_instant_kill if enabled?("instantKill")
                apply_noclip if enabled?("noClip")
                if enabled?("infiniteHp") || enabled?("infiniteMp")
                  party_members.each { |actor| apply_actor(actor) }
                end
                gain_gold(int_value("gold", 999999)) if enabled?("goldEnabled")
                current_nonce = nonce
                if @last_apply_nonce != current_nonce
                  @last_apply_nonce = current_nonce
                  gain_all_items if enabled?("allItems")
                  set_exp(int_value("exp", 999999)) if enabled?("expEnabled")
                end
              rescue
              end
            end

            if defined?(Graphics)
              class << Graphics
                unless method_defined?(:mkxpz_modifier_update_without_tick)
                  alias_method :mkxpz_modifier_update_without_tick, :update
                  def update(*args)
                    MKXPZPlayerModifier.tick
                    mkxpz_modifier_update_without_tick(*args)
                  end
                end
              end
            end
            """.trimIndent(),
        )
        return script
    }

    private companion object {
        private val soundFontExtensions = setOf("sf2", "sf3")
        private val soundFontCommonDirectories = listOf("", "Audio", "Fonts", "SoundFont", "SoundFonts", "System")
        private val soundFontSearchDirectories = setOf("audio", "fonts", "font", "soundfont", "soundfonts", "system")
    }
}

private val String.rubyStringLiteral: String
    get() = "\"" + buildString {
        this@rubyStringLiteral.forEach { char ->
            when (char) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(char)
            }
        }
    } + "\""

private fun File.writeTextIfChanged(text: String) {
    if (isFile && runCatching { readText() == text }.getOrDefault(false)) {
        return
    }
    writeText(text)
}

private fun parseIniValue(text: String, key: String): String {
    val prefix = "$key="
    return text.lineSequence()
        .firstOrNull { line -> line.trimStart().startsWith(prefix, ignoreCase = true) }
        ?.substringAfter("=")
        ?.trim()
        .orEmpty()
}
